sudo: required
services:
  - docker
install: true
jobs:
  include:
    - stage: pull_request
      if: type IN (pull_request)
      env:
        - ARTIFACT_ID=$TRAVIS_PULL_REQUEST
      script:
        - make build-docker-artifact

    - stage: continuous_integration
      if: NOT tag IS present AND type IN (push)
      env:
        - ARTIFACT_ID=$TRAVIS_COMMIT
      script:
        - make build-docker-artifact && make publish-docker-artifact && make publish-docker-edge

    - stage: release
      if: tag IS present
      env:
        - ARTIFACT_ID=$TRAVIS_COMMIT
        - RELEASE_VERSION=$TRAVIS_TAG
      script:
        - make publish-npm-release && make publish-docker-release
